<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Shared/Domain.fs" Link="Domain.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
